# SELECT B.AUTHOR_ID, AUTH.AUTHOR_NAME, B.CATEGORY, 
#        B.BOOK_ID,
#        SUM(SAL.SALES *B.PRICE) AS TOTAL_SALES  -- TOTAL_SALES = 판매량 * 판매가
# FROM BOOK B
#      INNER JOIN AUTHOR      AUTH    ON B.AUTHOR_ID = AUTH.AUTHOR_ID
#      INNER JOIN BOOK_SALES  SAL     ON B.BOOK_ID = SAL.BOOK_ID
# WHERE SAL.SALES_DATE LIKE '2022-01%'
# GROUP BY B.BOOK_ID
# ORDER BY 1, 3 DESC
SELECT 
    B.AUTHOR_ID,
    AUTH.AUTHOR_NAME,
    B.CATEGORY,
    SUM(SAL.SALES * B.PRICE) AS SALES
FROM 
    BOOK B
JOIN 
    AUTHOR AUTH ON B.AUTHOR_ID = AUTH.AUTHOR_ID
JOIN 
    BOOK_SALES SAL ON B.BOOK_ID = SAL.BOOK_ID
WHERE 
    SAL.SALES_DATE LIKE '2022-01%'
GROUP BY 
    B.AUTHOR_ID, AUTH.AUTHOR_NAME, B.CATEGORY
ORDER BY 
    B.AUTHOR_ID ASC, B.CATEGORY DESC;
