SELECT P.PRODUCT_CODE AS PRODUCT_CODE,
       SUM(P.PRICE * O.SALES_AMOUNT) AS SALES
-- 상품코드 별 매출액(판매가*판매량)의 합계

FROM PRODUCT AS P
     JOIN OFFLINE_SALE AS O
     ON P.PRODUCT_ID = O.PRODUCT_ID

GROUP BY P.PRODUCT_CODE

ORDER BY SALES DESC, PRODUCT_CODE