SELECT U.USER_ID,
       U.NICKNAME,
       CONCAT(U.CITY, ' ', U.STREET_ADDRESS1, ' ', U.STREET_ADDRESS2) AS 전체주소,
       CONCAT(SUBSTRING(U.TLNO, 1, 3), '-', SUBSTRING(U.TLNO, 4, 4), '-', SUBSTRING(U.TLNO, 8)) AS 전화번호

FROM USED_GOODS_BOARD AS B
     INNER JOIN USED_GOODS_USER AS U
     ON B.WRITER_ID = U.USER_ID

-- 중고 거래 게시물을 3건 이상 등록한 사용자
GROUP BY B.WRITER_ID
HAVING COUNT(B.TITLE) >=3
-- 결과는 회원 ID를 기준으로 내림차순 정렬해주세요.
ORDER BY U.USER_ID DESC
