SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME
-- 동물의 아이디와 생물 종, 이름을 조회하는 아이디 순으로 조회하는 SQL 문
FROM ANIMAL_INS I
     INNER JOIN ANIMAL_OUTS O
     ON I.ANIMAL_ID = O.ANIMAL_ID

# WHERE I.SEX_UPON_INTAKE LIKE 'Intact%'
#       AND (O.SEX_UPON_OUTCOME LIKE 'Neutered%'
#            OR O.SEX_UPON_OUTCOME LIKE 'Spayed%')

WHERE I.SEX_UPON_INTAKE  LIKE 'Intact%'
      AND (O.SEX_UPON_OUTCOME LIKE 'Neutered%'
          OR O.SEX_UPON_OUTCOME LIKE 'Spayed%')
      
ORDER BY I.ANIMAL_ID