SELECT DISTINCT DEV.ID, DEV.EMAIL, DEV.FIRST_NAME, DEV.LAST_NAME -- 개발자의 ID, 이메일, 이름, 성을 조회
FROM DEVELOPERS DEV
    INNER JOIN SKILLCODES SK
    ON SK.CODE & DEV.SKILL_CODE
WHERE SK.CATEGORY = 'Front End'
ORDER BY 1;