SELECT U.USER_ID, -- 회원 ID
       U.NICKNAME,  -- 닉네임
       SUM(B.PRICE) AS TOTAL_SALES -- 총거래금액

FROM USED_GOODS_BOARD AS B
     INNER JOIN USED_GOODS_USER AS U
     ON B.WRITER_ID = U.USER_ID

WHERE B.STATUS = "DONE"
      
GROUP BY B.WRITER_ID, U.USER_ID, U.NICKNAME, B.STATUS
HAVING SUM(B.PRICE) >= 700000

ORDER BY TOTAL_SALES