SELECT INFO.ID AS ID,
       NAME.FISH_NAME AS FISH_NAME,
       INFO.LENGTH AS LENGTH

FROM FISH_INFO AS INFO
     JOIN FISH_NAME_INFO AS NAME
     ON INFO.FISH_TYPE = NAME.FISH_TYPE

WHERE INFO.FISH_TYPE IN (
    SELECT FISH_TYPE
    FROM FISH_INFO
    GROUP BY FISH_TYPE
    HAVING LENGTH = MAX(LENGTH)
)

ORDER BY INFO.ID