SELECT DEP.DEPT_ID,
       DEP.DEPT_NAME_EN,
       ROUND(AVG(EMP.SAL),0) AS AVG_SAL
FROM HR_DEPARTMENT AS DEP
     INNER JOIN HR_EMPLOYEES AS EMP
     ON DEP.DEPT_ID = EMP.DEPT_ID
GROUP BY DEP.DEPT_ID
ORDER BY AVG_SAL DESC
